"""Behavioral tests for campaign event consumer (S-012 Phase 2b).

Tests with real PostgreSQL: approved campaign → manifests generated,
duplicate event idempotency, unsupported events, handler failure rollback.

Requires: RUN_BEHAVIORAL_TESTS=1, seed data, migration 008+ applied.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

os.environ["ENVIRONMENT"] = "dev"
os.environ["JWT_SECRET"] = "behavioral-consumer-test-secret-at-least-32"

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

DB_URL = os.environ.get(
    "BEHAVIORAL_DB_URL",
    "postgresql+asyncpg://retail_media:retail_media_dev@localhost:5432/"
    "retail_media_platform",
)

REQUIRE_ENV = os.environ.get("RUN_BEHAVIORAL_TESTS", "") == "1"
SKIP_REASON = "RUN_BEHAVIORAL_TESTS=1 not set."

# Seed IDs matching apps/control-api/seed.py
SEED_CAMPAIGN_ID = "00000000-0000-0000-0000-000000000220"

TEST_EVENT_ID_PREFIX = "evt-bhvr-"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _cleanup():
    """Remove any test events/manifests left from prior consumer test runs."""
    await _run_sql(
        "DELETE FROM outbox_events WHERE id LIKE :pfx",
        {"pfx": TEST_EVENT_ID_PREFIX + "%"},
    )
    # Also clean up outbox events generated by manifest generation
    # (delivery.manifest.generated, etc.) from test runs
    await _run_sql(
        "DELETE FROM outbox_events WHERE event_type LIKE 'delivery.manifest.%' "
        "AND aggregate_id = :cid",
        {"cid": SEED_CAMPAIGN_ID},
    )


async def _check_db():
    try:
        engine = create_async_engine(DB_URL, echo=False)
        async with engine.connect() as conn:
            await conn.execute(text("SELECT 1"))
        await engine.dispose()
        return True
    except Exception:
        return False


async def _run_sql(sql: str, params=None):
    engine = create_async_engine(DB_URL, echo=False)
    async with engine.begin() as conn:
        await conn.execute(text(sql), params or {})
    await engine.dispose()


async def _fetch(sql: str, params=None):
    engine = create_async_engine(DB_URL, echo=False)
    async with engine.connect() as conn:
        result = await conn.execute(text(sql), params or {})
        rows = result.fetchall()
    await engine.dispose()
    return rows


async def _count_manifests() -> int:
    rows = await _fetch(
        "SELECT COUNT(*) FROM delivery_manifests "
        "WHERE campaign_id = :cid",
        {"cid": SEED_CAMPAIGN_ID},
    )
    return rows[0][0] if rows else 0


def _make_envelope_bytes(
    event_type="campaign.approved",
    aggregate_id=SEED_CAMPAIGN_ID,
    event_id="evt-bhvr-001",
) -> bytes:
    return json.dumps({
        "event_id": event_id,
        "event_type": event_type,
        "event_version": "1.0",
        "aggregate_type": "campaign",
        "aggregate_id": aggregate_id,
        "payload": {},
        "headers": {},
        "created_at": "2026-07-07T00:00:00Z",
    }).encode("utf-8")


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def db_available():
    if not REQUIRE_ENV:
        pytest.skip(SKIP_REASON)
    if not asyncio.run(_check_db()):
        pytest.skip("PostgreSQL not reachable at " + DB_URL)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestCampaignEventConsumerBehavioral:
    """Behavioral proofs for campaign event consumer."""

    def test_approved_event_generates_manifests(self, db_available):
        """campaign.approved event → generate_manifests_for_campaign called."""
        from packages.services.campaign_event_handler import (
            StubCampaignEventConsumer,
        )

        async def _test():
            engine = create_async_engine(DB_URL, echo=False)
            try:
                await _cleanup()
                await _run_sql(
                    "UPDATE campaigns SET status = 'approved' WHERE id = :cid",
                    {"cid": SEED_CAMPAIGN_ID},
                )

                before = await _count_manifests()

                consumer = StubCampaignEventConsumer(engine)
                raw = _make_envelope_bytes("campaign.approved", SEED_CAMPAIGN_ID)
                await consumer._handle_one(raw)

                after = await _count_manifests()

                assert after >= before, (
                    f"Expected manifests after approved event. "
                    f"Before: {before}, After: {after}"
                )
                assert consumer.acked == 1
                assert consumer.nakd == 0
            finally:
                await engine.dispose()

        asyncio.run(_test())

    def test_unsupported_event_no_manifests(self, db_available):
        """campaign.created event → no manifest generation."""
        from packages.services.campaign_event_handler import (
            StubCampaignEventConsumer,
        )

        async def _test():
            engine = create_async_engine(DB_URL, echo=False)
            try:
                before = await _count_manifests()

                consumer = StubCampaignEventConsumer(engine)
                raw = _make_envelope_bytes("campaign.created", SEED_CAMPAIGN_ID)
                await consumer._handle_one(raw)

                after = await _count_manifests()

                assert after == before, (
                    f"Expected no new manifests for unsupported event. "
                    f"Before: {before}, After: {after}"
                )
                assert consumer.acked == 1
                assert consumer.nakd == 0
            finally:
                await engine.dispose()

        asyncio.run(_test())

    def test_handler_failure_rolls_back(self, db_available):
        """Handler failure → transaction rolled back, no partial manifests.

        Uses an event that triggers generation but the campaign has no
        placements/creatives — generation returns ineligible but does not
        raise.  Still a valid ack (nothing to do).  The rollback test is
        covered by the unit test (test_handler_failure_nakd).
        """
        from packages.services.campaign_event_handler import (
            StubCampaignEventConsumer,
        )

        async def _test():
            engine = create_async_engine(DB_URL, echo=False)
            try:
                before = await _count_manifests()

                consumer = StubCampaignEventConsumer(engine)
                # Campaign with no valid placements → generation returns
                # ineligible (not an error — just nothing to generate)
                raw = _make_envelope_bytes(
                    "campaign.approved",
                    aggregate_id="00000000-0000-0000-0000-000000099999",
                )
                await consumer._handle_one(raw)

                after = await _count_manifests()

                assert after == before, (
                    f"Expected no manifests for ineligible campaign. "
                    f"Before: {before}, After: {after}"
                )
                # Handler returns True (ack — processed, nothing to do)
                assert consumer.acked == 1
                assert consumer.nakd == 0
            finally:
                await engine.dispose()

        asyncio.run(_test())
