#!/usr/bin/env python3
"""One-time migration: legacy roadmap sources -> roadmap.yaml + disposition manifest (RM-GOV-002).

This script is a MIGRATION, not a generator. After the cutover (RM-GOV-005)
``docs/product/roadmap.yaml`` is maintained by hand and the *projections*
(roadmap.md / XLSX / metrics) are generated by RM-GOV-003. Re-running this
script is only meaningful while redoing the initial migration.

Inputs:
    docs/product/history/roadmap-s020-2026-07-10.xlsx   (legacy sheets, архив RM-GOV-005)
    docs/audit/2026-08-26-roadmap-task-breakdown-final-candidate.md   (+ v2 replacements)
    docs/product/feature-registry.yaml                   (blocked features)

Outputs:
    docs/product/roadmap-migration-manifest.yaml
    docs/product/roadmap.yaml

Usage:
    python3 scripts/dev/build-initial-roadmap.py [--dry-run]
"""

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

import openpyxl
import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
XLSX = ROOT / "docs" / "product" / "history" / "roadmap-s020-2026-07-10.xlsx"
CANDIDATE = ROOT / "docs" / "audit" / "2026-08-26-roadmap-task-breakdown-final-candidate.md"
REGISTRY = ROOT / "docs" / "product" / "feature-registry.yaml"
OUT_MANIFEST = ROOT / "docs" / "product" / "roadmap-migration-manifest.yaml"
OUT_ROADMAP = ROOT / "docs" / "product" / "roadmap.yaml"

STAGES = {"Этап G": "G", "Этап E0": "E0", "Этап S": "S",
          "Этап U": "U", "Этап B/T": "BT", "Этап P/OPS": "POPS"}

# --- disposition rules -------------------------------------------------------
# Domain keyword -> approved task that carries the residual work.
DOMAIN_TO_TASK = [
    (r"clickhouse",                        "RM-TECH-209"),
    (r"kso|плеер|player|playlist|плейлист", "RM-TECH-207A"),
    (r"licens|лиценз",                     "RM-TECH-208"),
    (r"недопоказ|underdeliver|компенсац",  "RM-TECH-201"),
    (r"приоритет|вытесн|preempt",          "RM-TECH-202"),
    (r"overbook",                          "RM-TECH-203"),
    (r"creative qa|антивирус|модерац|malware|вирус|scan", "RM-TECH-204"),
    (r"\bslo\b|\bsla\b|monitoring|observability|мониторинг", "RM-TECH-205"),
    (r"tenant|adr-018|multiten|мультиаренд", "RM-STAB-003"),
    (r"rls|rbac|scope|роли|права",         "RM-STAB-004"),
    (r"journey|юзер-стори",                "RM-STAB-006"),
    (r"ui-smoke|smoke",                    "RM-STAB-005"),
    (r"depend|requirement|версии",         "RM-STAB-009"),
    (r"подпис|signing|ed25519|hmac",       "RM-STAB-010"),
    (r"roadmap|guard",                     "RM-GOV-004"),
    (r"tls|production|прод|секрет|secret|ротац", "RM-OPS-001"),
    (r"pilot|пилот|deploy|развёрт",        "RM-PILOT-001"),
    (r"стенд|stand|окружени|environment",  "RM-ENV-001"),
    (r"backup|бэкап|restore|dr\b",         "RM-PILOT-002"),
]

# Rows whose recorded status contradicts verified current truth (audit 2026-08-26).
CONTRADICTED = {
    "Tenant Model ADR (ADR-018)": "ADR-018 принят 2026-07-17 и реализован (миграции 020/035); статус «в работе» неверен",
    "Production Observability": "production остаётся NO-GO; «Готово» не соответствует",
    "DR / Backups / HA": "production остаётся NO-GO; «Готово» не соответствует",
    "§22.6 Device fleet health dashboard": "device.health_view reachable с зелёным smoke; «Не начато» неверно",
    "§24 Channel Orchestrator / Adapter Layer": "ADR-019 ACCEPTED (deferred); «Требует решения» неверно",
}


def _norm(v):
    return re.sub(r"\s+", " ", str(v or "")).strip()


# Domains the audit proved duplicated across the legacy technical sheet (R3).
DUPLICATE_GROUPS = {
    "backup": r"backup|бэкап|restore|\bdr\b|резервн",
    "observability": r"observability|monitoring|мониторинг",
}

OPEN_STATUS_PREFIXES = ("⚪", "🧭", "🔒", "🚧", "🟠")

V26 = "домен v2.6 next branch; §10 запрещает активацию без нового owner decision"
OPEN_OUT = ("ОТКРЫТЫЙ пункт вне утверждённой очереди 42 задач — не закрыт, "
            "требует отдельного решения владельца")

# Explicit human review on top of the deterministic rules. Every override carries a reason;
# without this layer keyword matching mislabels v2.6 domains and anything containing
# "мониторинг" as an observability duplicate.
OVERRIDES = {
    "Competitive Separation":                ("history", V26, None),
    "Store-Level Audience Targeting":        ("history", V26, None),
    "Finance Contract/Invoicing Integration": ("history", V26, None),
    "Competitor blocking":                   ("history", V26, None),
    "Store/audience targeting":              ("history", V26, None),
    "Financial docs / reconciliation / integration": ("history", V26, None),
    "КСО (кассы самообслуживания)":          ("migrate", "физический канал КСО ведёт design-задача", "RM-TECH-207A"),
    "Личный кабинет рекламодателя":          ("migrate", "остаточное — отчёт план/факт рекламодателя", "RM-BIZ-003"),
    "Мониторинг недопоказов и компенсации":  ("migrate", "не observability, а таксономия причин недопоказа", "RM-TECH-201"),
    "SIEM/Wazuh + ИБ-мониторинг":            ("history", OPEN_OUT, None),
    "Часовые пояса и календарь показов":     ("history", OPEN_OUT, None),
    "§22.17 Timezone / calendar / holiday scheduling": ("history", OPEN_OUT, None),
    "Вход сотрудников / рекламодателей":     ("history", "self.login reachable; остаточное (self-service сброс пароля) — открытый пункт вне очереди", None),
    "✅ Готово: availability + reservation + conflicts + rules + UI calendar (S-081)":
        ("history", "инвентарь закрыт: inventory.simulate и inventory.rule_create reachable с зелёным smoke", None),
}


def classify(module, status, nextstep, seen_domains):
    """Deterministic disposition for one legacy row.

    Order matters: structural -> contradicted -> duplicate (narrow, name-only) ->
    deferred -> closed -> open work.
    """
    mod, st = _norm(module), _norm(status)
    blob = f"{mod} {st} {_norm(nextstep)}".lower()

    if mod.upper() == "SECTION":
        return "history", "структурный разделитель старого листа", None

    if mod in CONTRADICTED:
        return "drop-with-reason", CONTRADICTED[mod], None

    if mod in OVERRIDES:
        disp, reason, target = OVERRIDES[mod]
        return disp, f"[ручная поправка] {reason}", target

    # Duplicates are decided on the ROW NAME only, and only for domains the audit
    # actually proved duplicated. A broad match on free text would mislabel most rows.
    for group, pat in DUPLICATE_GROUPS.items():
        if re.search(pat, mod.lower()):
            if group in seen_domains:
                return ("deduplicate",
                        f"домен «{group}» уже описан строкой «{seen_domains[group]}»", None)
            seen_domains[group] = mod
            break

    if st.startswith("🚫"):
        return "history", "отложено решением владельца/ADR; §10 запрещает активацию без нового решения", None

    if st.startswith(OPEN_STATUS_PREFIXES):
        for pat, task in DOMAIN_TO_TASK:
            if re.search(pat, blob):
                return "migrate", "открытая работа перенесена в утверждённую задачу", task
        return ("history",
                OPEN_OUT, None)

    if st.startswith("✅") or st.startswith("🟡"):
        return "history", "работа закрыта; остаточных обязательств нет", None

    return "history", "нет остаточной работы, сопоставимой с утверждённой очередью", None


def build_manifest():
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    entries, counts = [], Counter()

    tech = wb["Технический Roadmap"]
    seen = {}
    for r in tech.iter_rows(min_row=2):
        if not any(c.value for c in r):
            continue
        mod, st, nxt = r[0].value, r[1].value, r[3].value if len(r) > 3 else ""
        disp, reason, target = classify(mod, st, nxt, seen)
        kind = "section" if _norm(mod).upper() == "SECTION" else "technical"
        counts[f"{kind}:{disp}"] += 1
        e = dict([("source", "technical-sheet"), ("row", r[0].row),
                         ("name", _norm(mod)), ("legacy_status", _norm(st)),
                         ("disposition", disp), ("reason", reason)])
        if target:
            e["target"] = target
        entries.append(e)

    biz = wb["Бизнес-функции Roadmap"]
    seen_b = {}
    for r in biz.iter_rows(min_row=2):
        if not any(c.value for c in r):
            continue
        name, st = r[1].value, r[5].value if len(r) > 5 else ""
        nxt = r[10].value if len(r) > 10 else ""
        disp, reason, target = classify(name, st, nxt, seen_b)
        counts[f"business:{disp}"] += 1
        e = dict([("source", "business-sheet"), ("row", r[0].row),
                         ("name", _norm(name)), ("legacy_status", _norm(st)),
                         ("disposition", disp), ("reason", reason)])
        if target:
            e["target"] = target
        entries.append(e)

    return entries, counts



# --- roadmap.yaml generation -------------------------------------------------
PREFIX = {"G": "GOV", "S": "STAB", "U": "UX", "B": "BIZ", "T": "TECH", "P": "PILOT", "E": "ENV"}


def _expand(token):
    """'G001–002' -> [RM-GOV-001, RM-GOV-002]; 'S010' -> [RM-STAB-010]; 'Gate G' -> [Gate-G]."""
    token = token.strip()
    if not token or token == "—":
        return []
    m = re.match(r"^Gate\s+([A-Z])$", token)
    if m:
        return [f"Gate-{m.group(1)}"]
    if token == "E0":
        return ["RM-ENV-001"]
    m = re.match(r"^([GSUBTPE])(\d{3})([AB]?)\s*[–-]\s*(\d{3})$", token)
    if m:
        pre, lo, _sfx, hi = m.groups()
        return [f"RM-{PREFIX[pre]}-{n:03d}" for n in range(int(lo), int(hi) + 1)]
    m = re.match(r"^([GSUBTPE])(\d{3})([AB]?)$", token)
    if m:
        pre, num, sfx = m.groups()
        return [f"RM-{PREFIX[pre]}-{num}{sfx}"]
    return []


def normalize_deps(raw):
    out = []
    # everything after '+' is an owner input/approval, not a dependency
    raw = raw.split("+")[0]
    for part in re.split(r",", raw):
        out.extend(_expand(part))
    seen, uniq = set(), []
    for d in out:
        if d not in seen:
            seen.add(d)
            uniq.append(d)
    return uniq


def extract_tasks():
    text = CANDIDATE.read_text(encoding="utf-8")
    stage, tasks = None, []
    for line in text.split("\n"):
        m = re.match(r"^## \d+\. (Этап [A-Z/0-9]+)", line)
        if m:
            stage = STAGES.get(m.group(1))
        r = re.match(
            r"^\|\s*\*\*(RM-[A-Z]+-\d+[AB]?)(?:\s*/\s*(A\w+))?\*\*\s*\|\s*([a-z\-]+)"
            r"\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$", line)
        if r:
            tid, alias, kind, title, deps, acc = r.groups()
            tasks.append({"id": tid, "alias": alias, "kind": kind, "stage": stage,
                          "title": title, "deps": normalize_deps(deps),
                          "acceptance_text": acc})
    return tasks



OWNER_DECISIONS = [
 ("OD-001","Код/тесты описывают фактическое поведение; ТЗ/ADR — требуемое. Расхождение является дефектом до явного ADR.","approved"),
 ("OD-002","Ed25519 обязателен для device pilot/production. HMAC допустим только для dev и control-plane stand.","approved"),
 ("OD-003","Retailer scope — первоклассная граница; bypass только system_admin и security_admin.","approved"),
 ("OD-004","UI-smoke отделён от ordinary pytest и является blocking gate для develop, release и повышения journey до reachable.","approved"),
 ("OD-005","self.campaign_create исключён из ближайшего control-plane pilot; первый pilot managed-first.","approved"),
 ("OD-006","При renewal занятые seats старого grant атомарно закрываются и продолжаются под новым grant.","approved"),
 ("OD-007","Активный baseline — .81 / stand-27dc397; .77 называется только unreachable at check time.","approved"),
 ("OD-008","MFA обязателен до production; согласование NATS с ИТ/ops — до pilot deployment.","open"),
]

BLOCKED = [
 ("self.campaign_create",["RM-BIZ-002"],["владелец включает self-service в scope пилота"],"OD-005"),
 ("self.report_view",["RM-BIZ-003"],["реальные PoP-события от плеера, а не симулятора"],None),
 ("playlist.build",["RM-TECH-207B"],["плеер перенесён в enterprise-репозиторий и есть реальный КСО"],None),
 ("license.view",["RM-TECH-208"],["signed-license Layer 2: offline Ed25519 verify + kid/CRL"],None),
 ("license.upload",["RM-TECH-208"],["signed-license Layer 2: upload .lic + проверка подписи"],None),
]

DONE = {"RM-GOV-001"}
IN_PROGRESS = {"RM-GOV-002"}


def build_roadmap(accept_map):
    sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT).decode().strip()
    tasks = []
    for t in extract_tasks():
        vb, ref, gate = accept_map[t["id"]]
        acc = {"check": t["acceptance_text"].split(";")[0].strip(), "verified_by": vb}
        if ref:
            acc["ref"] = ref
        entry = {
            "id": t["id"], "kind": t["kind"], "stage": t["stage"], "title": t["title"],
            "dependencies": t["deps"], "acceptance": [acc],
            "decision_status": "approved",
            "delivery_status": ("done" if t["id"] in DONE
                                else "in_progress" if t["id"] in IN_PROGRESS else "planned"),
            "notes": "полная приёмка — docs/audit/2026-08-26-roadmap-task-breakdown-final-candidate.md (+v2)",
        }
        if t["alias"]:
            entry["alias"] = t["alias"]
        if gate:
            entry["owner_gate"] = {"required": True, "reason": gate}
        if t["id"] in DONE:
            entry["evidence_refs"] = [
                {"kind": "command",
                 "ref": "python3 scripts/ci/check-roadmap-schema.py --self-test",
                 "status": "verified"},
                {"kind": "artifact",
                 "ref": "docs/architecture/rm-gov-001-roadmap-yaml-design-gate.md",
                 "status": "verified"},
            ]
        tasks.append(entry)

    return {
        "schema_version": 1,
        "base": {
            "git_sha": sha,
            "generated_from": "docs/audit/2026-08-26-roadmap-task-breakdown-final-candidate.md (+v2), утверждено владельцем 2026-08-26",
            "stand_baseline": {"name": "rmp-local-stand",
                               "git_sha": "27dc39707c5c56cdfdcc4250d5aa875d3789c8dc",
                               "bundle": "stand-27dc397", "schema_head": "036"},
        },
        "owner_decisions": [{"id": i, "statement": st, "status": stt,
                             **({"decided_on": "2026-08-26"} if stt == "approved" else {})}
                            for i, st, stt in OWNER_DECISIONS],
        "stages": [
            {"id": "G", "title": "Единая система roadmap", "order": 0, "closed_by_gate": "Gate-G"},
            {"id": "E0", "title": "Окружения", "order": 1},
            {"id": "S", "title": "Стабилизация доказательств и границ", "order": 2, "closed_by_gate": "Gate-S"},
            {"id": "U", "title": "Утверждённый UX-порядок", "order": 3, "closed_by_gate": "Gate-U"},
            {"id": "BT", "title": "Бизнесовые и технические разрывы", "order": 4},
            {"id": "POPS", "title": "Внешние действия: pilot и production", "order": 4},
        ],
        "gates": [
            {"id": "Gate-G", "closes_stage": "G", "approver": "owner",
             "conditions": ["Codex проверяет generator и tamper matrix", "владелец утверждает canonical cutover"]},
            {"id": "Gate-S", "closes_stage": "S", "approver": "codex",
             "conditions": ["новые counts и evidence воспроизводимы"]},
            {"id": "Gate-U", "closes_stage": "U", "approver": "human",
             "conditions": ["человек проходит walkthrough на exact stand bundle"]},
        ],
        "blocked_features": [
            {"feature_id": f, "unblocked_by": by, "conditions": c,
             **({"owner_decision": od} if od else {})}
            for f, by, c, od in BLOCKED
        ],
        "tasks": tasks,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    entries, counts = build_manifest()
    tech = [e for e in entries if e["source"] == "technical-sheet" and e["name"].upper() != "SECTION"]
    sect = [e for e in entries if e["name"].upper() == "SECTION"]
    biz = [e for e in entries if e["source"] == "business-sheet"]

    print(f"technical items : {len(tech)}")
    print(f"SECTION rows    : {len(sect)}")
    print(f"business rows   : {len(biz)}")
    print("dispositions    :", dict(sorted(counts.items())))

    if args.dry_run:
        return 0

    sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT).decode().strip()
    doc = dict([
        ("schema_version", 1),
        ("produced_by", "RM-GOV-002 via scripts/dev/build-initial-roadmap.py"),
        ("base_git_sha", sha),
        ("source_files", [str(XLSX.relative_to(ROOT))]),
        ("counts", dict([("technical_items", len(tech)),
                                ("section_rows", len(sect)),
                                ("business_rows", len(biz))])),
        ("dispositions", dict(sorted(counts.items()))),
        ("notes", [
            "Бизнес-лист: 58 непустых строк. Утверждённая приёмка называет 57 — разница ровно "
            "в строке 30, вырожденном разделителе с пустым именем (заполнена одна ячейка). "
            "Здесь диспозиция проставлена всем 58, ничего не потеряно.",
            "Диспозиция 'history' с пометкой ОТКРЫТЫЙ означает архивацию строки, а НЕ закрытие "
            "работы: такие пункты не покрыты ни одной из 42 утверждённых задач и требуют "
            "отдельного решения владельца.",
            "Записи с '[ручная поправка]' — там, где детерминированные правила ошибались; "
            "каждая несёт обоснование.",
        ]),
        ("entries", entries),
    ])
    OUT_MANIFEST.write_text(
        yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8")
    print(f"\nwrote {OUT_MANIFEST.relative_to(ROOT)}")

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from roadmap_acceptance_map import ACCEPT
    rm = build_roadmap(ACCEPT)
    OUT_ROADMAP.write_text(
        yaml.safe_dump(rm, allow_unicode=True, sort_keys=False, width=110),
        encoding="utf-8")
    print(f"wrote {OUT_ROADMAP.relative_to(ROOT)} ({len(rm['tasks'])} tasks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
