# id -> (verified_by, ref|None, owner_gate_reason|None)
ACCEPT = {
 "RM-GOV-001": ("command","python3 scripts/ci/check-roadmap-schema.py --self-test","scope_decision"),
 "RM-GOV-002": ("command","python3 scripts/ci/check-roadmap-schema.py --file docs/product/roadmap.yaml",None),
 "RM-GOV-003": ("command","python3 scripts/ci/roadmap-generate.py --check-clean-diff",None),
 "RM-GOV-004": ("ci_job","roadmap-governance-guard",None),
 "RM-GOV-006": ("artifact","docs/architecture/adr/ADR-020-fact-vs-requirement.md",None),
 "RM-GOV-005": ("owner",None,"canon_change"),
 "RM-ENV-001": ("artifact","docs/product/environment-inventory.yaml","scope_decision"),
 "RM-STAB-001": ("command","RUN_BEHAVIORAL_TESTS=1 python3 -m pytest tests/behavioral/test_commerce_rls.py -q",None),
 "RM-STAB-002": ("behavioral","tests/behavioral/conftest.py::strict get_db default",None),
 "RM-STAB-003": ("owner",None,"scope_decision"),
 "RM-STAB-006": ("command","python3 scripts/ci/check-journey-spec.py --strict",None),
 "RM-STAB-004": ("behavioral","tests/behavioral/test_retailer_scope_rbac.py","migration_application"),
 "RM-STAB-007": ("ui_smoke","tests/ui-smoke/ci-subset.txt (intended-role variants)",None),
 "RM-STAB-005": ("command","UI_SMOKE_RUN=1 python3 -m pytest tests/ui-contract -q",None),
 "RM-STAB-009": ("ci_job","python-tests (installs from requirements.txt)",None),
 "RM-STAB-010": ("artifact","docs/architecture/adr/ADR-021-manifest-signing-gate.md",None),
 "RM-STAB-008": ("ci_job","release-gate","canon_change"),
 "RM-STAB-011": ("command","python3 scripts/ci/check-roadmap-schema.py --file docs/product/roadmap.yaml",None),
 "RM-UX-001": ("artifact","docs/product/ux-route-matrix.yaml",None),
 "RM-UX-002": ("ui_smoke","tests/ui-smoke/test_uismoke__campaign__create.py",None),
 "RM-UX-003": ("artifact","docs/product/ux-responsive-report.yaml",None),
 "RM-UX-004": ("artifact","docs/product/ux-route-matrix.yaml (states coverage)",None),
 "RM-UX-005": ("ci_job","frontend",None),
 "RM-UX-006": ("artifact","docs/product/advertiser-route-matrix.yaml",None),
 "RM-UX-007": ("human",None,None),
 "RM-BIZ-001": ("artifact","docs/product/roadmap.yaml (pilot scope)",None),
 "RM-BIZ-002": ("ui_smoke","tests/ui-smoke/test_uismoke__self__campaign_create.py","scope_decision"),
 "RM-TECH-201": ("artifact","docs/product/underdelivery-reason-taxonomy.yaml",None),
 "RM-TECH-202": ("behavioral","tests/behavioral/test_campaign_preemption.py",None),
 "RM-TECH-203": ("behavioral","tests/behavioral/test_inventory_overbooking_policy.py",None),
 "RM-TECH-204": ("behavioral","tests/behavioral/test_creative_qa.py",None),
 "RM-TECH-205": ("artifact","docs/product/slo-objectives.yaml",None),
 "RM-TECH-206": ("behavioral","tests/behavioral/test_license_renewal_boundary.py",None),
 "RM-TECH-207A": ("artifact","docs/architecture/kso-environment-audit.md","scope_decision"),
 "RM-TECH-207B": ("behavioral","tests/behavioral/test_kso_playback_chain.py","device_contract"),
 "RM-BIZ-003": ("ui_smoke","tests/ui-smoke/test_uismoke__self__report_view.py",None),
 "RM-TECH-208": ("behavioral","tests/behavioral/test_signed_license_layer2.py","protected_boundary"),
 "RM-TECH-209": ("artifact","docs/product/clickhouse-capacity-trigger.yaml",None),
 "RM-PILOT-001": ("artifact","docs/runbook/pilot-scope.md",None),
 "RM-PILOT-002": ("artifact","infra/deploy/images.lock.json + dry-run evidence",None),
 "RM-PILOT-003": ("owner",None,"deployment"),
 "RM-OPS-001": ("owner",None,"deployment"),
}
